package tfschema

import (
	"github.com/alexmchughdev/terraform-provider-terradash/internal/dashboard"
	"github.com/alexmchughdev/terraform-provider-terradash/internal/schema"
)

const (
	ResourceType   = "terradash_dashboard"
	DataSourceType = "terradash_dashboard_json"
)

var Provider = schema.Block{
	Description: "Manage Grafana dashboards written in HCL.",
	Attributes: []schema.Attribute{
		{Name: "url", Kind: schema.String, Optional: true, Description: "Grafana base URL. Defaults to `GRAFANA_URL`."},
		{Name: "auth", Kind: schema.String, Optional: true, Sensitive: true, Description: "Service account token, `user:password` or `anonymous`. Defaults to `GRAFANA_AUTH`."},
		{Name: "org_id", Kind: schema.Number, Optional: true, Description: "Organization ID, for basic auth only. Defaults to `GRAFANA_ORG_ID`."},
		{Name: "ca_cert", Kind: schema.String, Optional: true, Description: "PEM CA bundle, or a path to one. Defaults to `GRAFANA_CA_CERT`."},
		{Name: "insecure_skip_verify", Kind: schema.Bool, Optional: true, Description: "Skip TLS verification. Defaults to `GRAFANA_INSECURE_SKIP_VERIFY`."},
		{Name: "http_headers", Kind: schema.StringMap, Optional: true, Sensitive: true, Description: "Extra headers sent with every request."},
		{Name: "retries", Kind: schema.Number, Optional: true, Description: "Retries for transient failures. Defaults to 3."},
		{Name: "timeout", Kind: schema.Number, Optional: true, Description: "Request timeout in seconds. Defaults to 60."},
	},
}

var Resource = schema.Block{
	Description: "A Grafana dashboard.",
	Attributes: concat(
		[]schema.Attribute{
			{Name: "uid", Kind: schema.String, Optional: true, Computed: true, Description: "Dashboard UID. Generated by Grafana when omitted; changing it recreates the dashboard."},
			{Name: "folder_uid", Kind: schema.String, Optional: true, Description: "UID of the folder to store the dashboard in. Defaults to the General folder."},
		},
		without(dashboard.Body.Attributes, "uid"),
		[]schema.Attribute{
			{Name: "overwrite", Kind: schema.Bool, Optional: true, Description: "Overwrite an existing dashboard with the same UID on create."},
			{Name: "message", Kind: schema.String, Optional: true, Description: "Version history message for changes."},
			{Name: "url", Kind: schema.String, Computed: true, Description: "Dashboard URL."},
			{Name: "version", Kind: schema.Number, Computed: true, Description: "Dashboard version."},
		},
	),
	Blocks: dashboard.Body.Blocks,
}

var DataSource = schema.Block{
	Description: "Renders a dashboard written in HCL to Grafana JSON without deploying it.",
	Attributes: concat(
		dashboard.Body.Attributes,
		[]schema.Attribute{{Name: "json", Kind: schema.String, Computed: true, Description: "Dashboard JSON model."}},
	),
	Blocks: dashboard.Body.Blocks,
}

func concat(lists ...[]schema.Attribute) []schema.Attribute {
	var out []schema.Attribute
	for _, l := range lists {
		out = append(out, l...)
	}
	return out
}

func without(attrs []schema.Attribute, name string) []schema.Attribute {
	var out []schema.Attribute
	for _, a := range attrs {
		if a.Name != name {
			out = append(out, a)
		}
	}
	return out
}
