package dashboard

import "github.com/alexmchughdev/terraform-provider-terradash/internal/schema"

type field struct {
	name     string
	key      string
	kind     schema.Kind
	desc     string
	required bool
	sub      []schema.Attribute
}

var gridPosAttributes = []schema.Attribute{
	{Name: "x", Kind: schema.Number, Optional: true, Description: "Column (0-23). Omit with `y` to auto-place."},
	{Name: "y", Kind: schema.Number, Optional: true, Description: "Row. Omit with `x` to auto-place."},
	{Name: "w", Kind: schema.Number, Optional: true, Description: "Width in grid columns (1-24). Defaults to 12."},
	{Name: "h", Kind: schema.Number, Optional: true, Description: "Height in grid rows. Defaults to 8."},
}

var timeAttributes = []schema.Attribute{
	{Name: "from", Kind: schema.String, Required: true},
	{Name: "to", Kind: schema.String, Required: true},
}

var dashboardFields = []field{
	{name: "uid", key: "uid", kind: schema.String, desc: "Dashboard UID. Generated by Grafana when omitted."},
	{name: "title", key: "title", kind: schema.String, required: true},
	{name: "description", key: "description", kind: schema.String},
	{name: "tags", key: "tags", kind: schema.StringList},
	{name: "timezone", key: "timezone", kind: schema.String, desc: "`browser`, `utc` or an IANA time zone."},
	{name: "week_start", key: "weekStart", kind: schema.String},
	{name: "refresh", key: "refresh", kind: schema.String, desc: "Auto-refresh interval, e.g. `30s`."},
	{name: "editable", key: "editable", kind: schema.Bool},
	{name: "graph_tooltip", key: "graphTooltip", kind: schema.Number, desc: "0 = default, 1 = shared crosshair, 2 = shared tooltip."},
	{name: "live_now", key: "liveNow", kind: schema.Bool},
	{name: "fiscal_year_start_month", key: "fiscalYearStartMonth", kind: schema.Number},
	{name: "schema_version", key: "schemaVersion", kind: schema.Number, desc: "Grafana dashboard schema version. Defaults to 41."},
	{name: "time", key: "time", kind: schema.Object, sub: timeAttributes, desc: "Default time range."},
	{name: "time_picker", key: "timepicker", kind: schema.Dynamic},
}

var panelFields = []field{
	{name: "id", key: "id", kind: schema.Number, desc: "Panel ID. Assigned automatically when omitted."},
	{name: "type", key: "type", kind: schema.String, desc: "Panel plugin ID, e.g. `timeseries`. Required unless `library_panel` is set."},
	{name: "title", key: "title", kind: schema.String},
	{name: "description", key: "description", kind: schema.String},
	{name: "grid_pos", key: "gridPos", kind: schema.Object, sub: gridPosAttributes, desc: "Position and size. Laid out automatically when omitted."},
	{name: "datasource", key: "datasource", kind: schema.Dynamic},
	{name: "targets", key: "targets", kind: schema.Dynamic, desc: "Queries, using Grafana's JSON keys."},
	{name: "options", key: "options", kind: schema.Dynamic},
	{name: "field_config", key: "fieldConfig", kind: schema.Dynamic},
	{name: "transformations", key: "transformations", kind: schema.Dynamic},
	{name: "links", key: "links", kind: schema.Dynamic},
	{name: "transparent", key: "transparent", kind: schema.Bool},
	{name: "interval", key: "interval", kind: schema.String},
	{name: "max_data_points", key: "maxDataPoints", kind: schema.Number},
	{name: "time_from", key: "timeFrom", kind: schema.String},
	{name: "time_shift", key: "timeShift", kind: schema.String},
	{name: "hide_time_override", key: "hideTimeOverride", kind: schema.Bool},
	{name: "repeat", key: "repeat", kind: schema.String},
	{name: "repeat_direction", key: "repeatDirection", kind: schema.String},
	{name: "max_per_row", key: "maxPerRow", kind: schema.Number},
	{name: "library_panel", key: "libraryPanel", kind: schema.Dynamic},
	{name: "plugin_version", key: "pluginVersion", kind: schema.String},
}

var rowFields = []field{
	{name: "id", key: "id", kind: schema.Number},
	{name: "title", key: "title", kind: schema.String},
	{name: "collapsed", key: "collapsed", kind: schema.Bool},
	{name: "grid_pos", key: "gridPos", kind: schema.Object, sub: gridPosAttributes},
	{name: "datasource", key: "datasource", kind: schema.Dynamic},
	{name: "repeat", key: "repeat", kind: schema.String},
}

var variableFields = []field{
	{name: "name", key: "name", kind: schema.String, required: true},
	{name: "type", key: "type", kind: schema.String, required: true, desc: "`query`, `custom`, `constant`, `datasource`, `interval`, `textbox`, `adhoc` or `groupby`."},
	{name: "label", key: "label", kind: schema.String},
	{name: "description", key: "description", kind: schema.String},
	{name: "hide", key: "hide", kind: schema.Number, desc: "0 = show, 1 = hide label, 2 = hide variable."},
	{name: "datasource", key: "datasource", kind: schema.Dynamic},
	{name: "query", key: "query", kind: schema.Dynamic},
	{name: "definition", key: "definition", kind: schema.String},
	{name: "regex", key: "regex", kind: schema.String},
	{name: "refresh", key: "refresh", kind: schema.Number},
	{name: "sort", key: "sort", kind: schema.Number},
	{name: "multi", key: "multi", kind: schema.Bool},
	{name: "include_all", key: "includeAll", kind: schema.Bool},
	{name: "all_value", key: "allValue", kind: schema.String},
	{name: "current", key: "current", kind: schema.Dynamic},
	{name: "options", key: "options", kind: schema.Dynamic},
	{name: "skip_url_sync", key: "skipUrlSync", kind: schema.Bool},
}

var annotationFields = []field{
	{name: "name", key: "name", kind: schema.String, required: true},
	{name: "enable", key: "enable", kind: schema.Bool},
	{name: "hide", key: "hide", kind: schema.Bool},
	{name: "icon_color", key: "iconColor", kind: schema.String},
	{name: "datasource", key: "datasource", kind: schema.Dynamic},
	{name: "built_in", key: "builtIn", kind: schema.Number},
	{name: "type", key: "type", kind: schema.String},
	{name: "target", key: "target", kind: schema.Dynamic},
	{name: "filter", key: "filter", kind: schema.Dynamic},
}

var linkFields = []field{
	{name: "title", key: "title", kind: schema.String},
	{name: "type", key: "type", kind: schema.String, desc: "`link` or `dashboards`."},
	{name: "url", key: "url", kind: schema.String},
	{name: "icon", key: "icon", kind: schema.String},
	{name: "tooltip", key: "tooltip", kind: schema.String},
	{name: "tags", key: "tags", kind: schema.StringList},
	{name: "as_dropdown", key: "asDropdown", kind: schema.Bool},
	{name: "include_vars", key: "includeVars", kind: schema.Bool},
	{name: "keep_time", key: "keepTime", kind: schema.Bool},
	{name: "target_blank", key: "targetBlank", kind: schema.Bool},
}

var extraAttribute = schema.Attribute{
	Name:        "extra",
	Kind:        schema.Dynamic,
	Optional:    true,
	Description: "Additional Grafana JSON keys merged verbatim. Must not repeat keys set by other arguments.",
}

func attributes(fields []field) []schema.Attribute {
	out := make([]schema.Attribute, 0, len(fields)+1)
	for _, f := range fields {
		out = append(out, schema.Attribute{
			Name:        f.name,
			Kind:        f.kind,
			Attributes:  f.sub,
			Description: f.desc,
			Required:    f.required,
			Optional:    !f.required,
		})
	}
	return append(out, extraAttribute)
}

var panelBlock = schema.Block{
	Name:        "panel",
	Description: "A dashboard panel. Free-form values use Grafana's JSON keys.",
	Attributes:  attributes(panelFields),
}

var rowBlock = schema.Block{
	Name:        "row",
	Description: "A row grouping the panels declared inside it.",
	Attributes:  attributes(rowFields),
	Blocks:      []schema.Block{panelBlock},
}

var variableBlock = schema.Block{Name: "variable", Description: "A template variable.", Attributes: attributes(variableFields)}

var annotationBlock = schema.Block{Name: "annotation", Description: "An annotation query.", Attributes: attributes(annotationFields)}

var linkBlock = schema.Block{Name: "link", Description: "A dashboard link.", Attributes: attributes(linkFields)}

// Body is the dashboard schema shared by the resource and data source.
var Body = schema.Block{
	Attributes: attributes(dashboardFields),
	Blocks:     []schema.Block{variableBlock, annotationBlock, linkBlock, panelBlock, rowBlock},
}
